<?php

return [
	'atm' => [
		32 => ['slug' =>'ha-noi','name' => 'Hà Nội','quan_huyen' => [1=>['name' => 'Ba Đình','slug' => 'ba-dinh'],2=>['name' => 'Cầu Giấy','slug' => 'cau-giay'],3=>['name' => 'Đống Đa','slug' => 'dong-da'],4=>['name' => 'Hà Đông','slug' => 'ha-dong'],5=>['name' => 'Hai Bà Trưng','slug' => 'hai-ba-trung'],6=>['name' => 'Hoàn Kiếm','slug' => 'hoan-kiem'],7=>['name' => 'Hoàng Mai','slug' => 'hoang-mai'],22=>['name' => 'Long Biên','slug' => 'long-bien'],23=>['name' => 'Tây Hồ','slug' => 'tay-ho'],24=>['name' => 'Thanh Xuân','slug' => 'thanh-xuan'],25=>['name' => 'Tx. Sơn Tây','slug' => 'tx-son-tay'],26=>['name' => 'Ba Vì','slug' => 'ba-vi'],27=>['name' => 'Chương Mỹ','slug' => 'chuong-my'],28=>['name' => 'Đan Phượng','slug' => 'dan-phuong'],29=>['name' => 'Đông Anh','slug' => 'dong-anh'],30=>['name' => 'Gia Lâm','slug' => 'gia-lam'],31=>['name' => 'Hoài Đức','slug' => 'hoai-duc'],32=>['name' => 'Mê Linh','slug' => 'me-linh'],33=>['name' => 'Mỹ Đức','slug' => 'my-duc'],34=>['name' => 'Phú Xuyên','slug' => 'phu-xuyen'],35=>['name' => 'Phúc Thọ','slug' => 'phuc-tho'],36=>['name' => 'Quốc Oai','slug' => 'quoc-oai'],37=>['name' => 'Sóc Sơn','slug' => 'soc-son'],38=>['name' => 'Thạch Thất','slug' => 'thach-that'],39=>['name' => 'Thanh Oai','slug' => 'thanh-oai'],40=>['name' => 'Thanh Trì','slug' => 'thanh-tri'],41=>['name' => 'Thường Tín','slug' => 'thuong-tin'],42=>['name' => 'Bắc Từ Liêm','slug' => 'bac-tu-liem'],43=>['name' => 'Ứng Hòa','slug' => 'ung-hoa'],759=>['name' => 'Nam Từ Liêm','slug' => 'nam-tu-liem'],]],
		33 => ['slug' =>'tp-hcm','name' => 'TP HCM','quan_huyen' => [44=>['name' => 'Bình Chánh','slug' => 'binh-chanh'],45=>['name' => 'Cần Giờ','slug' => 'can-gio'],46=>['name' => 'Củ Chi','slug' => 'cu-chi'],47=>['name' => 'Hóc Môn','slug' => 'hoc-mon'],48=>['name' => 'Nhà Bè','slug' => 'nha-be'],49=>['name' => 'Quận 1','slug' => 'quan-1'],50=>['name' => 'Quận 10','slug' => 'quan-10'],51=>['name' => 'Quận 11','slug' => 'quan-11'],52=>['name' => 'Quận 12','slug' => 'quan-12'],64=>['name' => 'Quận 2','slug' => 'quan-2'],65=>['name' => 'Quận 3','slug' => 'quan-3'],66=>['name' => 'Quận 4','slug' => 'quan-4'],67=>['name' => 'Quận 5','slug' => 'quan-5'],68=>['name' => 'Quận 6','slug' => 'quan-6'],69=>['name' => 'Quận 7','slug' => 'quan-7'],70=>['name' => 'Quận 8','slug' => 'quan-8'],71=>['name' => 'Quận 9 ','slug' => 'quan-9'],72=>['name' => 'Bình Tân','slug' => 'binh-tan'],73=>['name' => 'Bình Thạnh','slug' => 'binh-thanh'],74=>['name' => 'Gò Vấp','slug' => 'go-vap'],75=>['name' => 'Phú Nhuận','slug' => 'phu-nhuan'],76=>['name' => 'Tân Bình','slug' => 'tan-binh'],77=>['name' => 'Tân Phú','slug' => 'tan-phu'],78=>['name' => 'Thủ Đức','slug' => 'thu-duc'],]],
		34 => ['slug' =>'tp-can-tho','name' => 'TP Cần Thơ','quan_huyen' => [79=>['name' => 'H. Cờ Đỏ','slug' => 'h-co-do'],80=>['name' => 'H. Phong Điền','slug' => 'h-phong-dien'],81=>['name' => 'H. Thới Lai','slug' => 'h-thoi-lai'],82=>['name' => 'H. Vĩnh Thạnh','slug' => 'h-vinh-thanh'],83=>['name' => 'Bình Thủy','slug' => 'binh-thuy'],84=>['name' => 'Cái Răng','slug' => 'cai-rang'],85=>['name' => 'Ninh Kiều','slug' => 'ninh-kieu'],86=>['name' => 'Ô Môn','slug' => 'o-mon'],87=>['name' => 'Thốt Nốt','slug' => 'thot-not'],706=>['name' => 'TP Cần Thơ','slug' => 'tp-can-tho'],]],
		35 => ['slug' =>'tp-da-nang','name' => 'TP Đà Nẵng','quan_huyen' => [88=>['name' => 'H. Hòa Vang','slug' => 'h-hoa-vang'],89=>['name' => 'H. Hoàng Sa','slug' => 'h-hoang-sa'],90=>['name' => 'Cẩm Lệ','slug' => 'cam-le'],91=>['name' => 'Hải Châu','slug' => 'hai-chau'],92=>['name' => 'Liên Chiểu','slug' => 'lien-chieu'],93=>['name' => 'Ngũ Hành Sơn','slug' => 'ngu-hanh-son'],94=>['name' => 'Sơn Trà','slug' => 'son-tra'],95=>['name' => 'Thanh Khê','slug' => 'thanh-khe'],731=>['name' => 'Tp. Đà Nẵng','slug' => 'tp-da-nang'],743=>['name' => 'Ngô Quyền','slug' => 'ngo-quyen'],]],
		36 => ['slug' =>'tp-hai-phong','name' => 'TP Hải Phòng','quan_huyen' => [96=>['name' => 'H. An Dương','slug' => 'h-an-duong'],97=>['name' => 'H. An Lão','slug' => 'h-an-lao'],98=>['name' => 'H. Bạch Long Vĩ','slug' => 'h-bach-long-vi'],99=>['name' => 'H. Cát Hải','slug' => 'h-cat-hai'],100=>['name' => 'H. Kiến Thụy','slug' => 'h-kien-thuy'],101=>['name' => 'H. Thủy Nguyên','slug' => 'h-thuy-nguyen'],102=>['name' => 'H. Tiên Lãng','slug' => 'h-tien-lang'],103=>['name' => 'H. Vĩnh Bảo','slug' => 'h-vinh-bao'],104=>['name' => 'Đồ Sơn','slug' => 'do-son'],105=>['name' => 'Dương Kinh','slug' => 'duong-kinh'],106=>['name' => 'Hải An','slug' => 'hai-an'],107=>['name' => 'Hồng Bàng','slug' => 'hong-bang'],108=>['name' => 'Lê Chân','slug' => 'le-chan'],109=>['name' => 'Ngô Quyền','slug' => 'ngo-quyen'],688=>['name' => 'Kiến An','slug' => 'kien-an'],709=>['name' => 'Huyện Cát Bà','slug' => 'huyen-cat-ba'],745=>['name' => 'tp Hải Phòng','slug' => 'tp-hai-phong'],]],
		37 => ['slug' =>'an-giang','name' => 'An Giang','quan_huyen' => [110=>['name' => 'H. An Phú','slug' => 'h-an-phu'],111=>['name' => 'H. Châu Phú','slug' => 'h-chau-phu'],112=>['name' => 'H. Châu Thành','slug' => 'h-chau-thanh'],113=>['name' => 'H. Chợ Mới','slug' => 'h-cho-moi'],114=>['name' => 'H. Phú Tân','slug' => 'h-phu-tan'],115=>['name' => 'H. Thoại Sơn','slug' => 'h-thoai-son'],116=>['name' => 'H. Tịnh Biên','slug' => 'h-tinh-bien'],117=>['name' => 'H. Tri Tôn','slug' => 'h-tri-ton'],118=>['name' => 'tp Long Xuyên','slug' => 'tp-long-xuyen'],119=>['name' => 'tx Châu Đốc','slug' => 'tx-chau-doc'],120=>['name' => 'tx Tân Châu','slug' => 'tx-tan-chau'],717=>['name' => 'H. An Châu','slug' => 'h-an-chau'],]],
		38 => ['slug' =>'ba-ria-vung-tau','name' => 'Bà Rịa - Vũng Tàu','quan_huyen' => [121=>['name' => 'H. Châu Đức','slug' => 'h-chau-duc'],122=>['name' => 'H. Côn Đảo','slug' => 'h-con-dao'],123=>['name' => 'H. Đất Đỏ','slug' => 'h-dat-do'],124=>['name' => 'H. Long Điền','slug' => 'h-long-dien'],125=>['name' => 'H. Tân Thành','slug' => 'h-tan-thanh'],126=>['name' => 'H. Xuyên Mộc','slug' => 'h-xuyen-moc'],127=>['name' => 'tp Vũng Tàu','slug' => 'tp-vung-tau'],128=>['name' => 'tx Bà Rịa','slug' => 'tx-ba-ria'],720=>['name' => 'P.1','slug' => 'p1'],]],
		39 => ['slug' =>'bac-giang','name' => 'Bắc Giang','quan_huyen' => [129=>['name' => 'H. Hiệp Hòa','slug' => 'h-hiep-hoa'],130=>['name' => 'H. Lạng Giang','slug' => 'h-lang-giang'],131=>['name' => 'H. Lục Nam','slug' => 'h-luc-nam'],132=>['name' => 'H. Lục Ngạn','slug' => 'h-luc-ngan'],133=>['name' => 'H. Sơn Động','slug' => 'h-son-dong'],134=>['name' => 'H. Tân Yên','slug' => 'h-tan-yen'],135=>['name' => 'H. Yên Dũng','slug' => 'h-yen-dung'],136=>['name' => 'H. Yên Thế','slug' => 'h-yen-the'],137=>['name' => 'tp Bắc Giang','slug' => 'tp-bac-giang'],715=>['name' => 'H.Việt Yên','slug' => 'hviet-yen'],]],
		40 => ['slug' =>'bac-kan','name' => 'Bắc Kạn','quan_huyen' => [138=>['name' => 'H. Ba Bể','slug' => 'h-ba-be'],139=>['name' => 'H. Bạch Thông','slug' => 'h-bach-thong'],140=>['name' => 'H. Chợ Đồn','slug' => 'h-cho-don'],141=>['name' => 'H. Chợ Mới','slug' => 'h-cho-moi'],142=>['name' => 'H. Na Rì','slug' => 'h-na-ri'],143=>['name' => 'H. Ngân Sơn','slug' => 'h-ngan-son'],144=>['name' => 'H. Pác Nặm','slug' => 'h-pac-nam'],145=>['name' => 'tx Bắc Kạn','slug' => 'tx-bac-kan'],]],
		41 => ['slug' =>'bac-lieu','name' => 'Bạc Liêu','quan_huyen' => [146=>['name' => 'H. Đông Hải','slug' => 'h-dong-hai'],147=>['name' => 'H. Giá Rai','slug' => 'h-gia-rai'],148=>['name' => 'H. Hòa Bình','slug' => 'h-hoa-binh'],149=>['name' => 'H. Phước Long','slug' => 'h-phuoc-long'],150=>['name' => 'H. Vĩnh Lợi','slug' => 'h-vinh-loi'],151=>['name' => 'tp Bạc Liêu','slug' => 'tp-bac-lieu'],708=>['name' => 'Thị xã Bạc liêu','slug' => 'thi-xa-bac-lieu'],710=>['name' => 'Hồng Dân','slug' => 'hong-dan'],757=>['name' => 'Tx. Giá Rai','slug' => 'tx-gia-rai'],]],
		42 => ['slug' =>'bac-ninh','name' => 'Bắc Ninh','quan_huyen' => [152=>['name' => 'H. Gia Bình','slug' => 'h-gia-binh'],153=>['name' => 'H. Lương Tài','slug' => 'h-luong-tai'],154=>['name' => 'H. Quế Võ','slug' => 'h-que-vo'],155=>['name' => 'H. Thuận Thành','slug' => 'h-thuan-thanh'],156=>['name' => 'H. Tiên Du','slug' => 'h-tien-du'],157=>['name' => 'H. Yên Phong','slug' => 'h-yen-phong'],158=>['name' => 'tp Bắc Ninh','slug' => 'tp-bac-ninh'],159=>['name' => 'tx Từ Sơn','slug' => 'tx-tu-son'],736=>['name' => 'H. Tiên Sơn','slug' => 'h-tien-son'],]],
		43 => ['slug' =>'ben-tre','name' => 'Bến Tre','quan_huyen' => [160=>['name' => 'H. Ba Tri','slug' => 'h-ba-tri'],161=>['name' => 'H. Bình Đại','slug' => 'h-binh-dai'],162=>['name' => 'H. Châu Thành','slug' => 'h-chau-thanh'],163=>['name' => 'H. Chợ Lách','slug' => 'h-cho-lach'],164=>['name' => 'H. Giồng Trôm','slug' => 'h-giong-trom'],165=>['name' => 'H. Mỏ Cày Bắc','slug' => 'h-mo-cay-bac'],166=>['name' => 'H. Mỏ Cày Nam','slug' => 'h-mo-cay-nam'],167=>['name' => 'H. Thạnh Phú','slug' => 'h-thanh-phu'],168=>['name' => 'tp Bến Tre','slug' => 'tp-ben-tre'],]],
		44 => ['slug' =>'binh-dinh','name' => 'Bình Định','quan_huyen' => [169=>['name' => 'H. An Lão','slug' => 'h-an-lao'],170=>['name' => 'H. An Nhơn','slug' => 'h-an-nhon'],171=>['name' => 'H. Hoài Ân','slug' => 'h-hoai-an'],172=>['name' => 'H. Hoài Nhơn','slug' => 'h-hoai-nhon'],173=>['name' => 'H. Phù Mỹ','slug' => 'h-phu-my'],174=>['name' => 'H. Phù Cát','slug' => 'h-phu-cat'],175=>['name' => 'H. Tây Sơn','slug' => 'h-tay-son'],176=>['name' => 'H. Tuy Phước','slug' => 'h-tuy-phuoc'],177=>['name' => 'H. Vân Canh','slug' => 'h-van-canh'],178=>['name' => 'H. Vĩnh Thạnh','slug' => 'h-vinh-thanh'],179=>['name' => 'tp Quy Nhơn','slug' => 'tp-quy-nhon'],]],
		45 => ['slug' =>'binh-duong','name' => 'Bình Dương','quan_huyen' => [180=>['name' => 'H. Bến Cát','slug' => 'h-ben-cat'],181=>['name' => 'H. Dầu Tiếng','slug' => 'h-dau-tieng'],182=>['name' => 'H. Dĩ An','slug' => 'h-di-an'],183=>['name' => 'H. Phú Giáo','slug' => 'h-phu-giao'],184=>['name' => 'H. Tân Uyên','slug' => 'h-tan-uyen'],185=>['name' => 'H. Thuận An','slug' => 'h-thuan-an'],186=>['name' => 'tx Thủ Dầu Một','slug' => 'tx-thu-dau-mot'],729=>['name' => 'H. Bắc Tân Uyên ','slug' => 'h-bac-tan-uyen'],733=>['name' => 'H. Bàu Bàng','slug' => 'h-bau-bang'],749=>['name' => 'tp. Thủ Dầu Một','slug' => 'tp-thu-dau-mot'],754=>['name' => 'Tx. Thuận An','slug' => 'tx-thuan-an'],]],
		46 => ['slug' =>'binh-phuoc','name' => 'Bình Phước','quan_huyen' => [697=>['name' => 'Bù Đăng','slug' => 'bu-dang'],698=>['name' => 'Phước Long','slug' => 'phuoc-long'],699=>['name' => 'Bù Đốp','slug' => 'bu-dop'],700=>['name' => 'Lộc Ninh','slug' => 'loc-ninh'],701=>['name' => 'Bình Long','slug' => 'binh-long'],702=>['name' => 'Chơn Thành','slug' => 'chon-thanh'],703=>['name' => 'Đồng Phú','slug' => 'dong-phu'],704=>['name' => 'Đồng Xoài','slug' => 'dong-xoai'],737=>['name' => 'Hớn Quản','slug' => 'hon-quan'],738=>['name' => 'Bù Gia Mập','slug' => 'bu-gia-map'],750=>['name' => 'h. Đồng Phù','slug' => 'h-dong-phu'],]],
		47 => ['slug' =>'binh-thuan','name' => 'Bình Thuận','quan_huyen' => [187=>['name' => 'H. Đức Linh','slug' => 'h-duc-linh'],188=>['name' => 'H. Bắc Bình','slug' => 'h-bac-binh'],189=>['name' => 'H. Hàm Tân','slug' => 'h-ham-tan'],190=>['name' => 'H. Hàm Thuận Bắc','slug' => 'h-ham-thuan-bac'],191=>['name' => 'H. Hàm Thuận Nam','slug' => 'h-ham-thuan-nam'],192=>['name' => 'H. Phú Quí','slug' => 'h-phu-qui'],193=>['name' => 'H. Tánh Linh','slug' => 'h-tanh-linh'],194=>['name' => 'H. Tuy Phong','slug' => 'h-tuy-phong'],195=>['name' => 'tp Phan Thiết','slug' => 'tp-phan-thiet'],196=>['name' => 'tx La Gi','slug' => 'tx-la-gi'],]],
		48 => ['slug' =>'ca-mau','name' => 'Cà Mau','quan_huyen' => [197=>['name' => 'H. Cái Nước','slug' => 'h-cai-nuoc'],198=>['name' => 'H. Đầm Dơi','slug' => 'h-dam-doi'],199=>['name' => 'H. Năm Căn','slug' => 'h-nam-can'],200=>['name' => 'H. Ngọc Hiển','slug' => 'h-ngoc-hien'],201=>['name' => 'H. Thới Bình','slug' => 'h-thoi-binh'],202=>['name' => 'H. Trần Văn Thời','slug' => 'h-tran-van-thoi'],203=>['name' => 'H. U Minh','slug' => 'h-u-minh'],204=>['name' => 'tp Cà Mau','slug' => 'tp-ca-mau'],739=>['name' => 'Phú Tân','slug' => 'phu-tan'],740=>['name' => 'H. Tằm Rơi','slug' => 'h-tam-roi'],]],
		49 => ['slug' =>'cao-bang','name' => 'Cao Bằng','quan_huyen' => [205=>['name' => 'H. Bảo Lạc','slug' => 'h-bao-lac'],206=>['name' => 'H. Bảo Lâm','slug' => 'h-bao-lam'],207=>['name' => 'H. Hạ Lang','slug' => 'h-ha-lang'],208=>['name' => 'H. Hà Quảng','slug' => 'h-ha-quang'],209=>['name' => 'H. Hòa An','slug' => 'h-hoa-an'],210=>['name' => 'H. Nguyên Bình','slug' => 'h-nguyen-binh'],211=>['name' => 'H. Phục Hòa','slug' => 'h-phuc-hoa'],212=>['name' => 'H. Quảng Uyên','slug' => 'h-quang-uyen'],213=>['name' => 'H. Thạch An','slug' => 'h-thach-an'],214=>['name' => 'H. Thông Nông','slug' => 'h-thong-nong'],215=>['name' => 'H. Trà Lĩnh','slug' => 'h-tra-linh'],216=>['name' => 'H. Trùng Khánh','slug' => 'h-trung-khanh'],217=>['name' => 'tx Cao Bằng','slug' => 'tx-cao-bang'],]],
		50 => ['slug' =>'dak-lak','name' => 'Đăk Lăk','quan_huyen' => [218=>['name' => 'H. Buôn Đôn','slug' => 'h-buon-don'],219=>['name' => 'H. Cư Kuin','slug' => 'h-cu-kuin'],220=>['name' => 'H. Cư Mgar','slug' => 'h-cu-mgar'],221=>['name' => 'H. Ea Kar','slug' => 'h-ea-kar'],222=>['name' => 'H. Ea Súp','slug' => 'h-ea-sup'],223=>['name' => 'H. EaHleo','slug' => 'h-eahleo'],224=>['name' => 'H. Krông Ana','slug' => 'h-krong-ana'],225=>['name' => 'H. Krông Bông','slug' => 'h-krong-bong'],226=>['name' => 'H. Krông Buk','slug' => 'h-krong-buk'],227=>['name' => 'H. Krông Năng','slug' => 'h-krong-nang'],228=>['name' => 'H. Krông Pắc','slug' => 'h-krong-pac'],229=>['name' => 'H. Lắc','slug' => 'h-lac'],230=>['name' => 'H. MDrăk','slug' => 'h-mdrak'],231=>['name' => 'tp Buôn Ma Thuột','slug' => 'tp-buon-ma-thuot'],232=>['name' => 'tx Buôn Hồ','slug' => 'tx-buon-ho'],]],
		51 => ['slug' =>'dak-nong','name' => 'Đak Nông','quan_huyen' => [233=>['name' => 'H. Cư Jut','slug' => 'h-cu-jut'],234=>['name' => 'H. Đăk Glong','slug' => 'h-dak-glong'],235=>['name' => 'H. Đăk Mil','slug' => 'h-dak-mil'],236=>['name' => 'H. Đăk RLấp','slug' => 'h-dak-rlap'],237=>['name' => 'H. Đăk Song','slug' => 'h-dak-song'],238=>['name' => 'H. Krông Nô','slug' => 'h-krong-no'],239=>['name' => 'H. Tuy Đức','slug' => 'h-tuy-duc'],240=>['name' => 'tx Gia Nghĩa','slug' => 'tx-gia-nghia'],]],
		52 => ['slug' =>'dien-bien','name' => 'Điện Biên','quan_huyen' => [241=>['name' => 'H. Điện Biên','slug' => 'h-dien-bien'],242=>['name' => 'H. Điên Biên Đông','slug' => 'h-dien-bien-dong'],243=>['name' => 'H. Mường Chà','slug' => 'h-muong-cha'],244=>['name' => 'H. Mường Nhé','slug' => 'h-muong-nhe'],245=>['name' => 'H. Mường Áng','slug' => 'h-muong-ang'],246=>['name' => 'H. Tủa Chùa','slug' => 'h-tua-chua'],247=>['name' => 'H. Tuần Giáo','slug' => 'h-tuan-giao'],248=>['name' => 'tp Điện Biên Phủ','slug' => 'tp-dien-bien-phu'],249=>['name' => 'tx Mường Lay','slug' => 'tx-muong-lay'],]],
		53 => ['slug' =>'dong-nai','name' => 'Đồng Nai','quan_huyen' => [250=>['name' => 'H. Cẩm Mỹ','slug' => 'h-cam-my'],251=>['name' => 'H. ĐỊnh Quán','slug' => 'h-dinh-quan'],252=>['name' => 'H. Long Thành','slug' => 'h-long-thanh'],253=>['name' => 'H. Nhơn Trạch','slug' => 'h-nhon-trach'],254=>['name' => 'H. Tân Phú','slug' => 'h-tan-phu'],255=>['name' => 'H. Thống Nhất','slug' => 'h-thong-nhat'],256=>['name' => 'H. Trảng Bom','slug' => 'h-trang-bom'],257=>['name' => 'H. Vĩnh Cửu','slug' => 'h-vinh-cuu'],258=>['name' => 'H. Xuân Lộc','slug' => 'h-xuan-loc'],259=>['name' => 'tp Biên Hòa','slug' => 'tp-bien-hoa'],260=>['name' => 'tx Long Khánh','slug' => 'tx-long-khanh'],]],
		54 => ['slug' =>'dong-thap','name' => 'Đồng Tháp','quan_huyen' => [261=>['name' => 'H. Cao Lãnh','slug' => 'h-cao-lanh'],262=>['name' => 'H. Châu Thành','slug' => 'h-chau-thanh'],263=>['name' => 'H. Hồng Ngự','slug' => 'h-hong-ngu'],264=>['name' => 'H. Lai Vung','slug' => 'h-lai-vung'],265=>['name' => 'H. Lấp Vò','slug' => 'h-lap-vo'],266=>['name' => 'H. Tam Nông','slug' => 'h-tam-nong'],267=>['name' => 'H. Thanh Bình','slug' => 'h-thanh-binh'],268=>['name' => 'H. Tháp Mười','slug' => 'h-thap-muoi'],269=>['name' => 'tp Cao Lãnh','slug' => 'tp-cao-lanh'],270=>['name' => 'tx Hồng Ngự','slug' => 'tx-hong-ngu'],271=>['name' => 'tx Sa Đec','slug' => 'tx-sa-dec'],711=>['name' => 'Tân Hồng','slug' => 'tan-hong'],]],
		55 => ['slug' =>'gia-lai','name' => 'Gia Lai','quan_huyen' => [272=>['name' => 'H. Chư Păh','slug' => 'h-chu-pah'],273=>['name' => 'H. Chư Pưh','slug' => 'h-chu-puh'],274=>['name' => 'H. Chư Sê','slug' => 'h-chu-se'],275=>['name' => 'H. Chư Prông','slug' => 'h-chu-prong'],276=>['name' => 'H. Đăk Đoa','slug' => 'h-dak-doa'],277=>['name' => 'H. Đăk Pơ','slug' => 'h-dak-po'],278=>['name' => 'H. Đức Cơ','slug' => 'h-duc-co'],279=>['name' => 'H. Ia Grai','slug' => 'h-ia-grai'],280=>['name' => 'H. Ia Pa','slug' => 'h-ia-pa'],281=>['name' => 'H. Kbang','slug' => 'h-kbang'],282=>['name' => 'H. Kông Chro','slug' => 'h-kong-chro'],283=>['name' => 'H. Krông Pa','slug' => 'h-krong-pa'],284=>['name' => 'H. Mang Yang','slug' => 'h-mang-yang'],285=>['name' => 'H. Phú Thiện','slug' => 'h-phu-thien'],286=>['name' => 'tp Pleiku','slug' => 'tp-pleiku'],287=>['name' => 'tx Ayun Pa','slug' => 'tx-ayun-pa'],288=>['name' => 'tx An Khê','slug' => 'tx-an-khe'],713=>['name' => 'H. Lagrai','slug' => 'h-lagrai'],714=>['name' => 'H. Lapa','slug' => 'h-lapa'],]],
		56 => ['slug' =>'ha-giang','name' => 'Hà Giang','quan_huyen' => [289=>['name' => 'H. Bắc Mê','slug' => 'h-bac-me'],290=>['name' => 'H. Bắc Quang','slug' => 'h-bac-quang'],291=>['name' => 'H. Đồng Văn','slug' => 'h-dong-van'],292=>['name' => 'H. Hoàng Su Phì','slug' => 'h-hoang-su-phi'],293=>['name' => 'H. Mèo Vạc','slug' => 'h-meo-vac'],294=>['name' => 'H. Quán Bạ','slug' => 'h-quan-ba'],295=>['name' => 'H. Quang Bình','slug' => 'h-quang-binh'],296=>['name' => 'H. Vị Xuyên','slug' => 'h-vi-xuyen'],297=>['name' => 'H. Xín Mần','slug' => 'h-xin-man'],298=>['name' => 'H. Yên Minh','slug' => 'h-yen-minh'],299=>['name' => 'tp Hà Giang','slug' => 'tp-ha-giang'],]],
		57 => ['slug' =>'ha-nam','name' => 'Hà Nam','quan_huyen' => [300=>['name' => 'H. Bình Lục','slug' => 'h-binh-luc'],301=>['name' => 'H. Duy Tiên','slug' => 'h-duy-tien'],302=>['name' => 'H. Kim Bảng','slug' => 'h-kim-bang'],303=>['name' => 'H. Lý Nhân','slug' => 'h-ly-nhan'],304=>['name' => 'H. Thanh Liêm','slug' => 'h-thanh-liem'],305=>['name' => 'tp Phủ Lý','slug' => 'tp-phu-ly'],]],
		58 => ['slug' =>'ha-tinh','name' => 'Hà Tĩnh','quan_huyen' => [306=>['name' => 'H. Cẩm Xuyên','slug' => 'h-cam-xuyen'],307=>['name' => 'H. Can Lộc','slug' => 'h-can-loc'],308=>['name' => 'H. Đức Thọ','slug' => 'h-duc-tho'],309=>['name' => 'H. Hương Khê','slug' => 'h-huong-khe'],310=>['name' => 'H. Hương Sơn','slug' => 'h-huong-son'],311=>['name' => 'H. Kỳ Anh','slug' => 'h-ky-anh'],312=>['name' => 'H. Lộc Hà','slug' => 'h-loc-ha'],313=>['name' => 'H. Nghi Xuân','slug' => 'h-nghi-xuan'],314=>['name' => 'H. Thạch Hà','slug' => 'h-thach-ha'],315=>['name' => 'H. Vũ Quang','slug' => 'h-vu-quang'],316=>['name' => 'tp Hà Tĩnh','slug' => 'tp-ha-tinh'],317=>['name' => 'tx Hồng Lĩnh','slug' => 'tx-hong-linh'],]],
		59 => ['slug' =>'hai-duong','name' => 'Hải Dương','quan_huyen' => [318=>['name' => 'H. Bình Giang','slug' => 'h-binh-giang'],319=>['name' => 'H. Cẩm Giàng','slug' => 'h-cam-giang'],320=>['name' => 'H. Gia Lộc','slug' => 'h-gia-loc'],321=>['name' => 'H. Kim Thành','slug' => 'h-kim-thanh'],322=>['name' => 'H. Kinh Môn','slug' => 'h-kinh-mon'],323=>['name' => 'H. Nam Sách','slug' => 'h-nam-sach'],324=>['name' => 'H. Ninh Giang','slug' => 'h-ninh-giang'],325=>['name' => 'H. Thanh Hà','slug' => 'h-thanh-ha'],326=>['name' => 'H. Thanh Miện','slug' => 'h-thanh-mien'],327=>['name' => 'H. Tứ Kỳ','slug' => 'h-tu-ky'],328=>['name' => 'tp Hải Dương','slug' => 'tp-hai-duong'],329=>['name' => 'tx Chí Linh','slug' => 'tx-chi-linh'],]],
		60 => ['slug' =>'hau-giang','name' => 'Hậu Giang','quan_huyen' => [330=>['name' => 'H. Châu Thành','slug' => 'h-chau-thanh'],331=>['name' => 'H. Châu Thành A','slug' => 'h-chau-thanh-a'],332=>['name' => 'H. Long Mỹ','slug' => 'h-long-my'],333=>['name' => 'H. Phụng Hiệp','slug' => 'h-phung-hiep'],334=>['name' => 'H. Vị Thủy','slug' => 'h-vi-thuy'],335=>['name' => 'tp Vị Thanh','slug' => 'tp-vi-thanh'],336=>['name' => 'tx Ngã Bảy','slug' => 'tx-nga-bay'],721=>['name' => 'TX. Tân Hiệp','slug' => 'tx-tan-hiep'],]],
		61 => ['slug' =>'hoa-binh','name' => 'Hòa Bình','quan_huyen' => [337=>['name' => 'H. Cao Phong','slug' => 'h-cao-phong'],338=>['name' => 'H. Đà Bắc','slug' => 'h-da-bac'],339=>['name' => 'H. Kỳ Sơn','slug' => 'h-ky-son'],340=>['name' => 'H. Lạc Sơn','slug' => 'h-lac-son'],341=>['name' => 'H. Lạc Thủy','slug' => 'h-lac-thuy'],342=>['name' => 'H. Lương Sơn','slug' => 'h-luong-son'],343=>['name' => 'H. Mai Châu','slug' => 'h-mai-chau'],344=>['name' => 'H. Tân Lạc','slug' => 'h-tan-lac'],345=>['name' => 'H. Yên Thủy','slug' => 'h-yen-thuy'],346=>['name' => 'tp Hòa Bình','slug' => 'tp-hoa-binh'],705=>['name' => 'H. Kim Bôi','slug' => 'h-kim-boi'],]],
		62 => ['slug' =>'hung-yen','name' => 'Hưng Yên','quan_huyen' => [62=>['name' => 'Ân Thi','slug' => 'an-thi'],689=>['name' => 'Khoái Châu','slug' => 'khoai-chau'],690=>['name' => 'Kim Động','slug' => 'kim-dong'],691=>['name' => 'Mỹ Hào','slug' => 'my-hao'],692=>['name' => 'Phù Cừ ','slug' => 'phu-cu'],693=>['name' => 'Tiên Lữ','slug' => 'tien-lu'],694=>['name' => 'Văn Giang','slug' => 'van-giang'],695=>['name' => 'Văn Lâm','slug' => 'van-lam'],696=>['name' => 'Yên Mỹ','slug' => 'yen-my'],707=>['name' => 'TP Hưng Yên','slug' => 'tp-hung-yen'],]],
		63 => ['slug' =>'khanh-hoa','name' => 'Khánh Hòa','quan_huyen' => [347=>['name' => 'H. Cam Lâm','slug' => 'h-cam-lam'],348=>['name' => 'H. Diên Khánh','slug' => 'h-dien-khanh'],349=>['name' => 'H. Khánh Sơn','slug' => 'h-khanh-son'],350=>['name' => 'H. Khánh Vĩnh','slug' => 'h-khanh-vinh'],351=>['name' => 'H. Ninh Hòa','slug' => 'h-ninh-hoa'],352=>['name' => 'H. Trường Sa','slug' => 'h-truong-sa'],353=>['name' => 'H. Vạn Ninh','slug' => 'h-van-ninh'],354=>['name' => 'tp Nha Trang','slug' => 'tp-nha-trang'],355=>['name' => 'tx Cam Ranh','slug' => 'tx-cam-ranh'],722=>['name' => 'H. Cam Đức','slug' => 'h-cam-duc'],]],
		64 => ['slug' =>'kien-giang','name' => 'Kiên Giang','quan_huyen' => [356=>['name' => 'H. An Biên','slug' => 'h-an-bien'],357=>['name' => 'H. An Minh','slug' => 'h-an-minh'],358=>['name' => 'H. Châu Thành','slug' => 'h-chau-thanh'],359=>['name' => 'H. Giang Thành','slug' => 'h-giang-thanh'],360=>['name' => 'H. Giồng Riềng','slug' => 'h-giong-rieng'],361=>['name' => 'H. Gò Quao','slug' => 'h-go-quao'],362=>['name' => 'H. Hòn Đất','slug' => 'h-hon-dat'],363=>['name' => 'H. Kiên Hải','slug' => 'h-kien-hai'],364=>['name' => 'H. Kiên Lương','slug' => 'h-kien-luong'],365=>['name' => 'H. Phú Quốc','slug' => 'h-phu-quoc'],366=>['name' => 'H. Tân Hiệp','slug' => 'h-tan-hiep'],367=>['name' => 'H. U Minh Thượng','slug' => 'h-u-minh-thuong'],368=>['name' => 'H. Vĩnh Thuận','slug' => 'h-vinh-thuan'],369=>['name' => 'tp Rạch Giá','slug' => 'tp-rach-gia'],370=>['name' => 'tx Hà Tiên','slug' => 'tx-ha-tien'],]],
		65 => ['slug' =>'kon-tum','name' => 'Kon Tum','quan_huyen' => [371=>['name' => 'H. Đăk Glei','slug' => 'h-dak-glei'],372=>['name' => 'H. Đăk Hà','slug' => 'h-dak-ha'],373=>['name' => 'H. Đăk Tô','slug' => 'h-dak-to'],374=>['name' => 'H. Kon Plông','slug' => 'h-kon-plong'],375=>['name' => 'H. Kon Rẫy','slug' => 'h-kon-ray'],376=>['name' => 'H. Ngọc Hồi','slug' => 'h-ngoc-hoi'],377=>['name' => 'H. Sa Thầy','slug' => 'h-sa-thay'],378=>['name' => 'H. Tu Mơ Rông','slug' => 'h-tu-mo-rong'],379=>['name' => 'tp Kon Tum','slug' => 'tp-kon-tum'],]],
		66 => ['slug' =>'lai-chau','name' => 'Lai Châu','quan_huyen' => [380=>['name' => 'H. Mường Tè','slug' => 'h-muong-te'],381=>['name' => 'H. Phong Thổ','slug' => 'h-phong-tho'],382=>['name' => 'H. Sìn Hồ','slug' => 'h-sin-ho'],383=>['name' => 'H. Tam Đường','slug' => 'h-tam-duong'],384=>['name' => 'H. Tân Uyên','slug' => 'h-tan-uyen'],385=>['name' => 'H. Than Uyên','slug' => 'h-than-uyen'],386=>['name' => 'tx Lai Châu','slug' => 'tx-lai-chau'],]],
		67 => ['slug' =>'lam-dong','name' => 'Lâm Đồng','quan_huyen' => [683=>['name' => 'TP Da Lat','slug' => 'tp-da-lat'],684=>['name' => 'TP Bao Loc','slug' => 'tp-bao-loc'],685=>['name' => 'H Bao Lam','slug' => 'h-bao-lam'],686=>['name' => 'H Cat Tien','slug' => 'h-cat-tien'],687=>['name' => 'H Di Linh','slug' => 'h-di-linh'],712=>['name' => 'H Đức Trọng','slug' => 'h-duc-trong'],723=>['name' => 'H. Đa Huoai','slug' => 'h-da-huoai'],724=>['name' => 'Đạ Tẻh','slug' => 'da-teh'],725=>['name' => 'Đơn Dương','slug' => 'don-duong'],726=>['name' => 'h. Lạc Dương','slug' => 'h-lac-duong'],727=>['name' => 'h. Lâm Hà','slug' => 'h-lam-ha'],]],
		68 => ['slug' =>'lang-son','name' => 'Lạng Sơn','quan_huyen' => [387=>['name' => 'H. Bắc Sơn','slug' => 'h-bac-son'],388=>['name' => 'H. Bình Gia','slug' => 'h-binh-gia'],389=>['name' => 'H. Cao Lộc','slug' => 'h-cao-loc'],390=>['name' => 'H. Chi Lăng','slug' => 'h-chi-lang'],391=>['name' => 'H. Đình Lập','slug' => 'h-dinh-lap'],392=>['name' => 'H. Hữu Lũng','slug' => 'h-huu-lung'],393=>['name' => 'H. Lộc Bình','slug' => 'h-loc-binh'],394=>['name' => 'H. Tràng Định','slug' => 'h-trang-dinh'],395=>['name' => 'H. Văn Lãng','slug' => 'h-van-lang'],396=>['name' => 'H. Văn Quan','slug' => 'h-van-quan'],397=>['name' => 'tp Lạng Sơn','slug' => 'tp-lang-son'],728=>['name' => 'h. Đồng Đăng','slug' => 'h-dong-dang'],]],
		69 => ['slug' =>'lao-cai','name' => 'Lào Cai','quan_huyen' => [398=>['name' => 'H. Bắc Hà','slug' => 'h-bac-ha'],399=>['name' => 'H. Bảo Thắng','slug' => 'h-bao-thang'],400=>['name' => 'H. Bảo Yên','slug' => 'h-bao-yen'],401=>['name' => 'H. Bát Xát','slug' => 'h-bat-xat'],402=>['name' => 'H. Mường Khương','slug' => 'h-muong-khuong'],403=>['name' => 'H. Sapa','slug' => 'h-sapa'],404=>['name' => 'H. Simacai','slug' => 'h-simacai'],405=>['name' => 'H. Văn Bàn','slug' => 'h-van-ban'],406=>['name' => 'tp Lào Cai','slug' => 'tp-lao-cai'],]],
		70 => ['slug' =>'long-an','name' => 'Long An','quan_huyen' => [407=>['name' => 'H. Bến Lức','slug' => 'h-ben-luc'],408=>['name' => 'H. Cần Đước','slug' => 'h-can-duoc'],409=>['name' => 'H. Cần Giuộc','slug' => 'h-can-giuoc'],410=>['name' => 'H. Châu Thành','slug' => 'h-chau-thanh'],411=>['name' => 'H. Đức Hòa','slug' => 'h-duc-hoa'],412=>['name' => 'H. Đức Huệ','slug' => 'h-duc-hue'],413=>['name' => 'H. Mộc Hóa','slug' => 'h-moc-hoa'],414=>['name' => 'H. Tân Hưng','slug' => 'h-tan-hung'],415=>['name' => 'H. Tân Thạnh','slug' => 'h-tan-thanh'],416=>['name' => 'H. Tân Trụ','slug' => 'h-tan-tru'],417=>['name' => 'H. Thạnh Hóa','slug' => 'h-thanh-hoa'],418=>['name' => 'H. Thủ Thùa','slug' => 'h-thu-thua'],419=>['name' => 'H. Vĩnh Hưng','slug' => 'h-vinh-hung'],420=>['name' => 'tp Tân An','slug' => 'tp-tan-an'],718=>['name' => 'TX Kiến Tường','slug' => 'tx-kien-tuong'],719=>['name' => 'TX Tân An','slug' => 'tx-tan-an'],]],
		71 => ['slug' =>'nam-dinh','name' => 'Nam Định','quan_huyen' => [421=>['name' => 'H. Giao Thủy','slug' => 'h-giao-thuy'],422=>['name' => 'H. Hải Hậu','slug' => 'h-hai-hau'],423=>['name' => 'H. Mỹ Lộc','slug' => 'h-my-loc'],424=>['name' => 'H. Nam Trực','slug' => 'h-nam-truc'],425=>['name' => 'H. Nghĩa Hưng','slug' => 'h-nghia-hung'],426=>['name' => 'H. Trực Ninh','slug' => 'h-truc-ninh'],427=>['name' => 'H. Vụ Bản','slug' => 'h-vu-ban'],428=>['name' => 'H. Xuân Trường','slug' => 'h-xuan-truong'],429=>['name' => 'H. Ý Yên','slug' => 'h-y-yen'],430=>['name' => 'tp Nam Định','slug' => 'tp-nam-dinh'],]],
		72 => ['slug' =>'nghe-an','name' => 'Nghệ An','quan_huyen' => [431=>['name' => 'H. Anh Sơn','slug' => 'h-anh-son'],432=>['name' => 'H. Con Cuông','slug' => 'h-con-cuong'],433=>['name' => 'H. Diễn Châu','slug' => 'h-dien-chau'],434=>['name' => 'H. Đô Lương','slug' => 'h-do-luong'],435=>['name' => 'H. Hưng Nguyên','slug' => 'h-hung-nguyen'],436=>['name' => 'H. Kỳ Sơn','slug' => 'h-ky-son'],437=>['name' => 'H. Nghi Lộc','slug' => 'h-nghi-loc'],438=>['name' => 'H. Nghĩa Đàn','slug' => 'h-nghia-dan'],439=>['name' => 'H. Quế Phong','slug' => 'h-que-phong'],440=>['name' => 'H. Quỳ Châu','slug' => 'h-quy-chau'],441=>['name' => 'H. Quỳ Hợp','slug' => 'h-quy-hop'],442=>['name' => 'H. Quỳnh Lưu','slug' => 'h-quynh-luu'],443=>['name' => 'H. Tân Kỳ','slug' => 'h-tan-ky'],444=>['name' => 'H. Thanh Chương','slug' => 'h-thanh-chuong'],445=>['name' => 'H. Tương Dương','slug' => 'h-tuong-duong'],446=>['name' => 'H. Yên Thành','slug' => 'h-yen-thanh'],447=>['name' => 'tp Vinh','slug' => 'tp-vinh'],448=>['name' => 'tx Cửa Lò','slug' => 'tx-cua-lo'],449=>['name' => 'tx Thái Hòa','slug' => 'tx-thai-hoa'],730=>['name' => 'h. Nam Đàn','slug' => 'h-nam-dan'],758=>['name' => 'Thị xã Hoàng Mai','slug' => 'thi-xa-hoang-mai'],]],
		73 => ['slug' =>'ninh-binh','name' => 'Ninh Bình','quan_huyen' => [450=>['name' => 'H. Gia Viễn','slug' => 'h-gia-vien'],451=>['name' => 'H. Hoa Lư','slug' => 'h-hoa-lu'],452=>['name' => 'H. Kim Sơn','slug' => 'h-kim-son'],453=>['name' => 'H. Nho Quan','slug' => 'h-nho-quan'],454=>['name' => 'H. Yên Khánh','slug' => 'h-yen-khanh'],455=>['name' => 'H. Yên Mô','slug' => 'h-yen-mo'],456=>['name' => 'tp Ninh Bình','slug' => 'tp-ninh-binh'],457=>['name' => 'tx Tam Điệp','slug' => 'tx-tam-diep'],]],
		74 => ['slug' =>'ninh-thuan','name' => 'Ninh Thuận','quan_huyen' => [458=>['name' => 'H. Bắc Ái','slug' => 'h-bac-ai'],459=>['name' => 'H. Ninh Hải','slug' => 'h-ninh-hai'],460=>['name' => 'H. Ninh Phước','slug' => 'h-ninh-phuoc'],461=>['name' => 'H. Ninh Sơn','slug' => 'h-ninh-son'],462=>['name' => 'H. Thuận Bắc','slug' => 'h-thuan-bac'],463=>['name' => 'H. Thuận Nam','slug' => 'h-thuan-nam'],464=>['name' => 'tp Phan Rang - Tháp Chàm','slug' => 'tp-phan-rang-thap-cham'],732=>['name' => 'TX. Phan Rang','slug' => 'tx-phan-rang'],]],
		75 => ['slug' =>'phu-tho','name' => 'Phú Thọ','quan_huyen' => [465=>['name' => 'H. Cẩm Khê','slug' => 'h-cam-khe'],466=>['name' => 'H. Đoan Hùng','slug' => 'h-doan-hung'],467=>['name' => 'H. Hạ Hòa','slug' => 'h-ha-hoa'],468=>['name' => 'H. Lâm Thao','slug' => 'h-lam-thao'],469=>['name' => 'H. Phù Ninh','slug' => 'h-phu-ninh'],470=>['name' => 'H. Tam Nông','slug' => 'h-tam-nong'],471=>['name' => 'H. Tân Sơn','slug' => 'h-tan-son'],472=>['name' => 'H. Thanh Ba','slug' => 'h-thanh-ba'],473=>['name' => 'H. Thanh Sơn','slug' => 'h-thanh-son'],474=>['name' => 'H. Thanh Thủy','slug' => 'h-thanh-thuy'],475=>['name' => 'H. Yên Lập','slug' => 'h-yen-lap'],476=>['name' => 'tp Việt Trì','slug' => 'tp-viet-tri'],477=>['name' => 'tx Phú Thọ','slug' => 'tx-phu-tho'],]],
		76 => ['slug' =>'phu-yen','name' => 'Phú Yên','quan_huyen' => [478=>['name' => 'H. Đông Hòa','slug' => 'h-dong-hoa'],479=>['name' => 'H. Đồng Xuân','slug' => 'h-dong-xuan'],480=>['name' => 'H. Phú Hòa','slug' => 'h-phu-hoa'],481=>['name' => 'H. Sơn Hòa','slug' => 'h-son-hoa'],482=>['name' => 'H. Sông Hinh','slug' => 'h-song-hinh'],483=>['name' => 'H. Tây Hòa','slug' => 'h-tay-hoa'],484=>['name' => 'H. Tuy An','slug' => 'h-tuy-an'],485=>['name' => 'tp Tuy Hòa','slug' => 'tp-tuy-hoa'],486=>['name' => 'tx Sông Cầu','slug' => 'tx-song-cau'],]],
		77 => ['slug' =>'quang-binh','name' => 'Quảng Bình','quan_huyen' => [487=>['name' => 'H. Bố Trạch','slug' => 'h-bo-trach'],488=>['name' => 'H. Lệ Thủy','slug' => 'h-le-thuy'],489=>['name' => 'H. Minh Hóa','slug' => 'h-minh-hoa'],490=>['name' => 'H. Quảng Ninh','slug' => 'h-quang-ninh'],491=>['name' => 'H. Quảng Trạch','slug' => 'h-quang-trach'],492=>['name' => 'H. Tuyên Hóa','slug' => 'h-tuyen-hoa'],493=>['name' => 'tp Đồng Hới','slug' => 'tp-dong-hoi'],751=>['name' => 'tx Ba Đồn','slug' => 'tx-ba-don'],]],
		78 => ['slug' =>'quang-nam','name' => 'Quảng Nam','quan_huyen' => [494=>['name' => 'H. Bắc Trà My','slug' => 'h-bac-tra-my'],495=>['name' => 'H. Đại Lộc','slug' => 'h-dai-loc'],496=>['name' => 'H. Điện Bàn','slug' => 'h-dien-ban'],497=>['name' => 'H. Đông Giang','slug' => 'h-dong-giang'],498=>['name' => 'H. Duy Xuyên','slug' => 'h-duy-xuyen'],499=>['name' => 'H. Hiệp Đức','slug' => 'h-hiep-duc'],500=>['name' => 'H. Nam Giang','slug' => 'h-nam-giang'],501=>['name' => 'H. Nam Trà My','slug' => 'h-nam-tra-my'],502=>['name' => 'H. Nông Sơn','slug' => 'h-nong-son'],503=>['name' => 'H. Núi Thành','slug' => 'h-nui-thanh'],504=>['name' => 'H. Phú Ninh','slug' => 'h-phu-ninh'],505=>['name' => 'H. Phước Sơn','slug' => 'h-phuoc-son'],506=>['name' => 'H. Quê Sơn','slug' => 'h-que-son'],507=>['name' => 'H. Tây Giang','slug' => 'h-tay-giang'],508=>['name' => 'H. Thăng Bình','slug' => 'h-thang-binh'],509=>['name' => 'H. Tiên Phước','slug' => 'h-tien-phuoc'],510=>['name' => 'tp Hội An','slug' => 'tp-hoi-an'],511=>['name' => 'tp Tam Kỳ','slug' => 'tp-tam-ky'],742=>['name' => 'H, Quế Sơn','slug' => 'h-que-son'],]],
		79 => ['slug' =>'quang-ngai','name' => 'Quảng Ngãi','quan_huyen' => [512=>['name' => 'H. Ba Tơ','slug' => 'h-ba-to'],513=>['name' => 'H. Bình Sơn','slug' => 'h-binh-son'],514=>['name' => 'H. Đức Phổ','slug' => 'h-duc-pho'],515=>['name' => 'H. Lý Sơn','slug' => 'h-ly-son'],516=>['name' => 'H. Minh Long','slug' => 'h-minh-long'],517=>['name' => 'H. Mộ Đức','slug' => 'h-mo-duc'],518=>['name' => 'H. Nghĩa Hành','slug' => 'h-nghia-hanh'],519=>['name' => 'H. Sơn Hà','slug' => 'h-son-ha'],520=>['name' => 'H. Sơn Tây','slug' => 'h-son-tay'],521=>['name' => 'H. Sơn Tịnh','slug' => 'h-son-tinh'],522=>['name' => 'H. Tây Trà','slug' => 'h-tay-tra'],523=>['name' => 'H. Trà Bồng','slug' => 'h-tra-bong'],524=>['name' => 'H. Tư Nghĩa','slug' => 'h-tu-nghia'],525=>['name' => 'tp Quảng Ngãi','slug' => 'tp-quang-ngai'],]],
		80 => ['slug' =>'quang-ninh','name' => 'Quảng Ninh','quan_huyen' => [526=>['name' => 'H. Ba Chẽ','slug' => 'h-ba-che'],527=>['name' => 'H. Bình Liêu','slug' => 'h-binh-lieu'],528=>['name' => 'H. Cô Tô','slug' => 'h-co-to'],529=>['name' => 'H. Đầm Hà','slug' => 'h-dam-ha'],530=>['name' => 'H. Đông Triều','slug' => 'h-dong-trieu'],531=>['name' => 'H. Hải hà','slug' => 'h-hai-ha'],532=>['name' => 'H. Hoành Bồ','slug' => 'h-hoanh-bo'],533=>['name' => 'H. Tiên Yên','slug' => 'h-tien-yen'],534=>['name' => 'H. Vân Đồn','slug' => 'h-van-don'],535=>['name' => 'H. Yên Hưng','slug' => 'h-yen-hung'],536=>['name' => 'tp Hạ Long','slug' => 'tp-ha-long'],537=>['name' => 'tp Móng Cái','slug' => 'tp-mong-cai'],538=>['name' => 'tx Cẩm Phả','slug' => 'tx-cam-pha'],539=>['name' => 'tx Uông Bí','slug' => 'tx-uong-bi'],741=>['name' => 'Tx Quảng Yên','slug' => 'tx-quang-yen'],752=>['name' => 'Tp. Cẩm Phả','slug' => 'tp-cam-pha'],753=>['name' => 'Tp. Uông Bí','slug' => 'tp-uong-bi'],]],
		81 => ['slug' =>'quang-tri','name' => 'Quảng Trị','quan_huyen' => [540=>['name' => 'H. Cam Lộ','slug' => 'h-cam-lo'],541=>['name' => 'H. Cồn Cỏ','slug' => 'h-con-co'],542=>['name' => 'H. Đa Krông','slug' => 'h-da-krong'],543=>['name' => 'H. Gio Linh','slug' => 'h-gio-linh'],544=>['name' => 'H. Hải Lăng','slug' => 'h-hai-lang'],545=>['name' => 'H. Hướng Hóa','slug' => 'h-huong-hoa'],546=>['name' => 'H. Triệu Phong','slug' => 'h-trieu-phong'],547=>['name' => 'H. Vĩnh Linh','slug' => 'h-vinh-linh'],548=>['name' => 'tp Đông Hà','slug' => 'tp-dong-ha'],549=>['name' => 'tx Quảng Trị','slug' => 'tx-quang-tri'],]],
		82 => ['slug' =>'soc-trang','name' => 'Sóc Trăng','quan_huyen' => [550=>['name' => 'H. Châu Thành','slug' => 'h-chau-thanh'],551=>['name' => 'H. Cù Lao Dung','slug' => 'h-cu-lao-dung'],552=>['name' => 'H. Kế Sách','slug' => 'h-ke-sach'],553=>['name' => 'H. Long Phú','slug' => 'h-long-phu'],554=>['name' => 'H. Mỹ Tú','slug' => 'h-my-tu'],555=>['name' => 'H. Mỹ Xuyên','slug' => 'h-my-xuyen'],556=>['name' => 'H. Ngã Năm','slug' => 'h-nga-nam'],557=>['name' => 'H. Thạnh Trị','slug' => 'h-thanh-tri'],558=>['name' => 'H. Trần Đề','slug' => 'h-tran-de'],559=>['name' => 'H. Vĩnh Châu','slug' => 'h-vinh-chau'],560=>['name' => 'tp Sóc Trăng','slug' => 'tp-soc-trang'],734=>['name' => 'TX. Sóc Trăng','slug' => 'tx-soc-trang'],]],
		83 => ['slug' =>'son-la','name' => 'Sơn La','quan_huyen' => [561=>['name' => 'H. Bắc Yên','slug' => 'h-bac-yen'],562=>['name' => 'H. Mai Sơn','slug' => 'h-mai-son'],563=>['name' => 'H. Mộc Châu','slug' => 'h-moc-chau'],564=>['name' => 'H. Mường La','slug' => 'h-muong-la'],565=>['name' => 'H. Phù Yên','slug' => 'h-phu-yen'],566=>['name' => 'H. Quỳnh Nhai','slug' => 'h-quynh-nhai'],567=>['name' => 'H. Sông Mã','slug' => 'h-song-ma'],568=>['name' => 'H. Sốp Cộp','slug' => 'h-sop-cop'],569=>['name' => 'H. Thuận Châu','slug' => 'h-thuan-chau'],570=>['name' => 'H. Yên Châu','slug' => 'h-yen-chau'],571=>['name' => 'tp Sơn La','slug' => 'tp-son-la'],]],
		84 => ['slug' =>'tay-ninh','name' => 'Tây Ninh','quan_huyen' => [572=>['name' => 'H. Bến Cầu','slug' => 'h-ben-cau'],573=>['name' => 'H. Châu Thành','slug' => 'h-chau-thanh'],574=>['name' => 'H. Dương Minh Châu','slug' => 'h-duong-minh-chau'],575=>['name' => 'H. Gò Dầu','slug' => 'h-go-dau'],576=>['name' => 'H. Hòa Thành','slug' => 'h-hoa-thanh'],577=>['name' => 'H. Tân Biên','slug' => 'h-tan-bien'],578=>['name' => 'H. Tân Châu','slug' => 'h-tan-chau'],579=>['name' => 'H. Trảng Bàng','slug' => 'h-trang-bang'],580=>['name' => 'tx Tây Ninh','slug' => 'tx-tay-ninh'],]],
		85 => ['slug' =>'thai-binh','name' => 'Thái Bình','quan_huyen' => [581=>['name' => 'H. Đông Hưng','slug' => 'h-dong-hung'],582=>['name' => 'H. Hưng Hà','slug' => 'h-hung-ha'],583=>['name' => 'H. Kiến Xương','slug' => 'h-kien-xuong'],584=>['name' => 'H. Quỳnh Phụ','slug' => 'h-quynh-phu'],585=>['name' => 'H. Thái Thụy','slug' => 'h-thai-thuy'],586=>['name' => 'H. Tiền Hải','slug' => 'h-tien-hai'],587=>['name' => 'H. Vũ Thư','slug' => 'h-vu-thu'],588=>['name' => 'tp Thái Bình','slug' => 'tp-thai-binh'],]],
		86 => ['slug' =>'thai-nguyen','name' => 'Thái Nguyên','quan_huyen' => [589=>['name' => 'H. Đại Từ','slug' => 'h-dai-tu'],590=>['name' => 'H. Định Hóa','slug' => 'h-dinh-hoa'],591=>['name' => 'H. Đồng Hỷ','slug' => 'h-dong-hy'],592=>['name' => 'H. Phổ yên','slug' => 'h-pho-yen'],593=>['name' => 'H. Phú Bình','slug' => 'h-phu-binh'],594=>['name' => 'H. Võ Nhai','slug' => 'h-vo-nhai'],595=>['name' => 'tp Thái Nguyên','slug' => 'tp-thai-nguyen'],596=>['name' => 'tx Sông Công','slug' => 'tx-song-cong'],735=>['name' => 'Phú Lương','slug' => 'phu-luong'],]],
		87 => ['slug' =>'thanh-hoa','name' => 'Thanh Hóa','quan_huyen' => [597=>['name' => 'H. Bá Thước','slug' => 'h-ba-thuoc'],598=>['name' => 'H. Cẩm Thủy','slug' => 'h-cam-thuy'],599=>['name' => 'H. Đông Sơn','slug' => 'h-dong-son'],600=>['name' => 'H. Hà Trung','slug' => 'h-ha-trung'],601=>['name' => 'H. Hậu Lộc','slug' => 'h-hau-loc'],602=>['name' => 'H. Hoằng Hóa','slug' => 'h-hoang-hoa'],603=>['name' => 'H. Lang Chánh','slug' => 'h-lang-chanh'],604=>['name' => 'H. Mường Lát','slug' => 'h-muong-lat'],605=>['name' => 'H. Nga Sơn','slug' => 'h-nga-son'],606=>['name' => 'H. Ngọc Lặc','slug' => 'h-ngoc-lac'],607=>['name' => 'H. Như Thanh','slug' => 'h-nhu-thanh'],608=>['name' => 'H. Như Xuân','slug' => 'h-nhu-xuan'],609=>['name' => 'H. Nông Cống','slug' => 'h-nong-cong'],610=>['name' => 'H. Quan Hóa','slug' => 'h-quan-hoa'],611=>['name' => 'H. Quan Sơn','slug' => 'h-quan-son'],612=>['name' => 'H. Quảng Xương','slug' => 'h-quang-xuong'],613=>['name' => 'H. Thạch Thành','slug' => 'h-thach-thanh'],614=>['name' => 'H. Thiệu Hóa','slug' => 'h-thieu-hoa'],615=>['name' => 'H. Thọ Xuân','slug' => 'h-tho-xuan'],616=>['name' => 'H. Thường Xuân','slug' => 'h-thuong-xuan'],617=>['name' => 'H. Tĩnh Gia','slug' => 'h-tinh-gia'],618=>['name' => 'H. Triệu Sơn','slug' => 'h-trieu-son'],619=>['name' => 'H. Vĩnh Lộc','slug' => 'h-vinh-loc'],620=>['name' => 'H. Yên Định','slug' => 'h-yen-dinh'],621=>['name' => 'tp Thanh Hóa','slug' => 'tp-thanh-hoa'],622=>['name' => 'tx Bỉm Sơn','slug' => 'tx-bim-son'],623=>['name' => 'tx Sầm Sơn','slug' => 'tx-sam-son'],]],
		88 => ['slug' =>'thua-thien-hue','name' => 'Thừa Thiên Huế','quan_huyen' => [624=>['name' => 'H. A Lưới','slug' => 'h-a-luoi'],625=>['name' => 'H. Hương Trà','slug' => 'h-huong-tra'],626=>['name' => 'H. Nam Đông','slug' => 'h-nam-dong'],627=>['name' => 'H. Phong Điền','slug' => 'h-phong-dien'],628=>['name' => 'H. Phú Lộc','slug' => 'h-phu-loc'],629=>['name' => 'H. Phú Vang','slug' => 'h-phu-vang'],630=>['name' => 'H. Quảng Điền','slug' => 'h-quang-dien'],631=>['name' => 'tp Huế','slug' => 'tp-hue'],632=>['name' => 'tx Hương Thủy','slug' => 'tx-huong-thuy'],]],
		89 => ['slug' =>'tien-giang','name' => 'Tiền Giang','quan_huyen' => [633=>['name' => 'H. Cái Bè','slug' => 'h-cai-be'],634=>['name' => 'H. Cai Lậy','slug' => 'h-cai-lay'],635=>['name' => 'H. Châu Thành','slug' => 'h-chau-thanh'],636=>['name' => 'H. Chợ Gạo','slug' => 'h-cho-gao'],637=>['name' => 'H. Gò Công Đông','slug' => 'h-go-cong-dong'],638=>['name' => 'H. Gò Công Tây','slug' => 'h-go-cong-tay'],639=>['name' => 'H. Tân Phú Đông','slug' => 'h-tan-phu-dong'],640=>['name' => 'H. Tân Phước','slug' => 'h-tan-phuoc'],641=>['name' => 'tp Mỹ Tho','slug' => 'tp-my-tho'],642=>['name' => 'tx Gò Công','slug' => 'tx-go-cong'],747=>['name' => 'TX. Cai Lậy','slug' => 'tx-cai-lay'],]],
		90 => ['slug' =>'tra-vinh','name' => 'Trà Vinh','quan_huyen' => [643=>['name' => 'H. Càng Long','slug' => 'h-cang-long'],644=>['name' => 'H. Cầu Kè','slug' => 'h-cau-ke'],645=>['name' => 'H. Cầu Ngang','slug' => 'h-cau-ngang'],646=>['name' => 'H. Châu Thành','slug' => 'h-chau-thanh'],647=>['name' => 'H. Duyên Hải','slug' => 'h-duyen-hai'],648=>['name' => 'H. Tiểu Cần','slug' => 'h-tieu-can'],649=>['name' => 'H. Trà Cú','slug' => 'h-tra-cu'],650=>['name' => 'tp Trà Vinh','slug' => 'tp-tra-vinh'],]],
		91 => ['slug' =>'tuyen-quang','name' => 'Tuyên Quang','quan_huyen' => [651=>['name' => 'H. Chiêm Hóa','slug' => 'h-chiem-hoa'],652=>['name' => 'H. Hàm Yên','slug' => 'h-ham-yen'],653=>['name' => 'H. Na Hang','slug' => 'h-na-hang'],654=>['name' => 'H. Sơn Dương','slug' => 'h-son-duong'],655=>['name' => 'H. Yên Sơn','slug' => 'h-yen-son'],656=>['name' => 'tp Tuyên Quang','slug' => 'tp-tuyen-quang'],]],
		92 => ['slug' =>'vinh-long','name' => 'Vĩnh Long','quan_huyen' => [657=>['name' => 'H. Bình Minh','slug' => 'h-binh-minh'],658=>['name' => 'H. Bình Tân','slug' => 'h-binh-tan'],659=>['name' => 'H. Long Hồ','slug' => 'h-long-ho'],660=>['name' => 'H. Mang Thít','slug' => 'h-mang-thit'],661=>['name' => 'H. Tam Bình','slug' => 'h-tam-binh'],662=>['name' => 'H. Trà Ôn','slug' => 'h-tra-on'],663=>['name' => 'H. Vũng Liêm','slug' => 'h-vung-liem'],664=>['name' => 'tp Vĩnh Long','slug' => 'tp-vinh-long'],748=>['name' => 'TX. Bình Minh','slug' => 'tx-binh-minh'],]],
		93 => ['slug' =>'vinh-phuc','name' => 'Vĩnh Phúc','quan_huyen' => [665=>['name' => 'H. Bình Xuyên','slug' => 'h-binh-xuyen'],666=>['name' => 'H. Lập Thạch','slug' => 'h-lap-thach'],667=>['name' => 'H. Sông Lô','slug' => 'h-song-lo'],668=>['name' => 'H. Tam Đảo','slug' => 'h-tam-dao'],669=>['name' => 'H. Tam Dương','slug' => 'h-tam-duong'],670=>['name' => 'H. Vĩnh Tường','slug' => 'h-vinh-tuong'],671=>['name' => 'H. Yên Lạc','slug' => 'h-yen-lac'],672=>['name' => 'tp Vĩnh Yên','slug' => 'tp-vinh-yen'],673=>['name' => 'tx Phúc Yên','slug' => 'tx-phuc-yen'],744=>['name' => 'tp Vĩnh Phúc','slug' => 'tp-vinh-phuc'],746=>['name' => 'H. Mê Linh','slug' => 'h-me-linh'],]],
		94 => ['slug' =>'yen-bai','name' => 'Yên Bái','quan_huyen' => [674=>['name' => 'H. Lục Yên','slug' => 'h-luc-yen'],675=>['name' => 'H. Mù Cang Chải','slug' => 'h-mu-cang-chai'],676=>['name' => 'H. Trạm Tấu','slug' => 'h-tram-tau'],677=>['name' => 'H. Trấn Yên','slug' => 'h-tran-yen'],678=>['name' => 'H. Văn Chấn','slug' => 'h-van-chan'],679=>['name' => 'H. Văn Yên','slug' => 'h-van-yen'],680=>['name' => 'H. Yên Bình','slug' => 'h-yen-binh'],681=>['name' => 'tp Yên Bái','slug' => 'tp-yen-bai'],682=>['name' => 'tx Nghĩa Lộ','slug' => 'tx-nghia-lo'],]],
			],
	'bank' => [
		2 => [
			'the_bank' => 'vietinbank',
			'the_bank_id' => 40
		],
		8 => [
			'the_bank' => 'maritime-bank',
			'the_bank_id' => 5
		],
		11 => [
			'the_bank' => 'sacombank',
			'the_bank_id' => 6
		],
		3 => [
			'the_bank' => 'acb',
			'the_bank_id' => 10
		],
		10 => [
			'the_bank' => 'vpbank',
			'the_bank_id' => 12
		],
		9 => [
			'the_bank' => 'techcombank',
			'the_bank_id' => 13
		],
		6 => [
			'the_bank' => 'mbbank',
			'the_bank_id' => 14
		],
		1 => [
			'the_bank' => 'vietcombank',
			'the_bank_id' => 39
		],
		4 => [
			'the_bank' => 'bidv',
			'the_bank_id' => 41
		],
		5 => [
			'the_bank' => 'agribank',
			'the_bank_id' => 42
		],
		7 => [
			'the_bank' => 'seabank',
			'the_bank_id' => 17
		]
	]
];